title: neuPrint API Guide hands on Tutorial
authors:
  - name: Sapolnach Prompiengchai
    affiliations:
      - University of Oxford
  - name: Aarushi Vardhan
    affiliations:
      - University of Toronto / University of Cambridge

In [1]:
# 1. load your packages at the top
import pandas as pd
import plotly.express as px
from neuprint import Client
c = Client('neuprint.janelia.org', dataset='male-cns:v1.0', token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhcnVzaGkudmFyZGhhbkBnbWFpbC5jb20iLCJsZXZlbCI6Im5vYXV0aCIsImltYWdlLXVybCI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0xlOVNycVUyYjl6bXZFM29wb2QyRFFLOWJlTThQRDgyT2lid25CVG01R0UtMGtWT3c9czk2LWM_c3o9NTA_c3o9NTAiLCJleHAiOjE5NjU4MTAxNTB9.lpFdEuQJ-k7toc1X7FavtQ95X-b5pgszBcv9V4zTzHI')

# Let's explore the fly's brain with neuPrint!

Let's start with a region of the fly brain called the **mushroom body (MB)**. Before we start exploring it with neuPrint, let's find out what makes this part of the brain so interesting.

## Why is it called the mushroom body?

Take a look at the image below. Can you see why scientists gave this structure its name?

When viewed under a microscope, the mushroom body has a shape that looks surprisingly similar to a **mushroom**! Scientists can make the structure easier to see using **GFP (green fluorescent protein)**, which makes the neurons glow green.

:::{image} ../static/mb.jpg
:alt: GFP-labeled Drosophila mushroom body
:width: 500px
:align: center
:caption: Figure 1: Drosophila mushroom body. Figure courtesy of Katrin Vogt.
:::

The mushroom body is found in the brains of many invertebrates, including insects, spiders, and scorpions.

In the fruit fly *Drosophila melanogaster*, the mushroom body contains roughly **2,500 neurons**, most of which are small neurons called **Kenyon cells**.

## What does the mushroom body look like?

Let's zoom in.

:::{image} ../static/mb_zoom.png
:alt: Zoomed-in view of the Drosophila mushroom body
:width: 500px
:align: center
:caption: Figure 2: Drosophila mushroom body. Figure courtesy of Campbell and Turner, 2010.
:::

There are a few important parts to notice:

- **Calyx** — where Kenyon cells receive information from other neurons.
- **Stalk** — where the axons of Kenyon cells bundle together.
- **Lobes** — where Kenyon cells send information to other parts of the brain.

You can think of the mushroom body as a place where information comes in, gets processed, and is then sent out to other parts of the brain.

And this is where neuPrint becomes really useful.

> **Connectomics question:**  
> Instead of only looking at a picture of the mushroom body, we can use the fly's connectome to ask: **Who is connected to whom?**

## So, what does the mushroom body actually do?

This is where things get really interesting.

The mushroom body is involved in **learning and memory**.

For example, researchers can train a fly to associate a particular smell with something unpleasant, such as an electric shock. After learning this association, the fly can change its behavior when it encounters that smell again.

Scientists have found that the mushroom body is essential for this type of learning. When researchers block the output of the mushroom body, flies have difficulty performing these learned behaviors.

This raises a really interesting question:

> **How can a network of neurons help a fly learn?**

We can start investigating this question using the connectome.

# Uncovering How a Brain Learns

Imagine that a fly encounters a smell.

Information about that smell travels through the brain and eventually reaches the **mushroom body**.

A simplified version of this pathway looks something like:

> **Smell → sensory neurons → mushroom body → other neurons → behavior**

The mushroom body doesn't work alone. It receives information from other parts of the brain and sends information to neurons downstream.

This gives us several questions that we can investigate using **neuPrint**.

## Let's Start Simple

We know that the mushroom body contains thousands of **Kenyon cells**. But 2,500 neurons is a lot of neurons!

Do all of these neurons do the same thing?

Or are different Kenyon cells connected to different parts of the brain?

Using neuPrint, we can explore the connections of individual Kenyon cells and see where their information goes.

## Challenge 1: Meet a Kenyon Cell

Let's explore the Kenyon Cell type (Cell type: a group of cells that are classified into a type based on morphology and connectivity) and explore its connections.

1. **Which neurons send information into the mushroom body?**
2. **Which neurons receive information from the mushroom body?**
3. **Are some neurons more strongly connected than others?**
4. **Do many neurons converge onto a small number of downstream neurons?**
5. **Can we find anything in the connectome that might help explain how learning works?**

> **Think like a scientist:**  
> Don't worry about finding the "right" answer immediately. Start by exploring the connections and see what patterns you can find.

In [3]:
# Step 1: if we go to the neuPrint documentation and head over to https://connectome-neuprint.github.io/neuprint-python/docs/notebooks/QueryTutorial.html#Fetch-connections
# Fetch connections¶. We see we can use this to fetch connections between neurons and their strength (number of synapses).
# We will also need Neuron Criteria as this will help fine tune our search to exactly the brain regions we want (MB) or the cell type( Kenyon cell) 

# First we run this: 
from neuprint import fetch_adjacencies, NeuronCriteria as NC
neuron_df, conn_df = fetch_adjacencies(NC(type='KC.*'), NC(type='KC.*'))

  0%|          | 0/21 [00:00<?, ?it/s]

0it [00:00, ?it/s]

In [4]:
neuron_df

      bodyId        type      instance
0      11862      KCab-s      KCab-s_L
1      13173      KCab-c      KCab-c_R
2      14292       KCg-m       KCg-m_R
3      15103       KCg-m       KCg-m_R
4      17488  KCa'b'-ap2  KCa'b'-ap2_R
...      ...         ...           ...
4059  919290      KCab-c      KCab-c_L
4060  923406      KCab-s      KCab-s_R
4061  945591      KCab-m      KCab-m_L
4062  946152      KCab-s      KCab-s_R
4063  953362      KCab-m      KCab-m_L

[4064 rows x 3 columns]

In [5]:
conn_df

        bodyId_pre  bodyId_post                       roi  weight
0            11862        42111  CentralBrain-unspecified       1
1            11862        47193                     aL(L)       2
2            11862        48030                     aL(L)       3
3            11862        52704                     aL(L)       2
4            11862        52824                     aL(L)       1
...            ...          ...                       ...     ...
782840      953362       580809                     aL(L)       2
782841      953362       581393                     bL(L)       1
782842      953362       915829                     aL(L)       1
782843      953362       945591                     bL(L)       1
782844      953362       945591                     gL(L)       1

[782845 rows x 4 columns]

A bigger question: how does a fly remember?

Here's something scientists find particularly interesting about the mushroom body.

Kenyon cells can be very selective in the way they respond to sensory information. Rather than having lots of Kenyon cells respond strongly to every smell, only a relatively small subset may respond to a particular stimulus.

This is called a sparse representation.

You can think of it like a giant light board containing thousands of lights. Instead of turning on every light when the fly smells something, only a small number of lights turn on.

Different smells can therefore produce different patterns of active Kenyon cells.

This leads to a fascinating possibility:

Could different patterns of Kenyon cell activity help the fly distinguish between different experiences?

We can use the connectome to start exploring how these neurons are wired together.

Can we find a "hub" in the mushroom body?

Networks often contain highly connected nodes called hubs.

Your next challenge is to see whether the mushroom body contains neurons that are unusually well connected.

Try finding neurons that:

receive input from many different neurons;
send output to many different neurons;
receive particularly strong connections; or
connect to many different cell types.

Then ask:

What might happen if this neuron were turned off?

You won't be able to answer that question from connectivity alone. But you can make a hypothesis.

And that is one of the most important things you can do with a connectome.

A connectome doesn't just tell us where neurons are. It allows us to ask questions about how information might flow through the brain.

From connections to hypotheses

At this point, you have explored:

neurons → connections → networks → behavior

Now it's your turn to be the scientist.

Choose a neuron in the mushroom body and use its connectivity to make a prediction:

What do you think this neuron might do?

There isn't necessarily one correct answer.

The goal is to use the wiring of the brain to make a testable hypothesis.

This is how we can use neuPrint to go from simply looking at a fly brain to actually asking questions about how the brain works.